name: Get ASN

on:
  workflow_dispatch:

jobs:
  get-asn:
    runs-on: ubuntu-latest
    steps:
      - name: Get public IP
        run: curl -s https://api.ipify.org > ip.txt

      - name: Print IP
        run: cat ip.txt

      - name: Lookup ASN
        run: |
          IP=$(cat ip.txt)
          curl -s https://ipinfo.io/$IP/org
