name: CI Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build

  test-api:
    runs-on: ubuntu-latest
    needs: build
    env:
      TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Run live API tests
        run: node .github/workflows/test-api.mjs
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }} 